#!/usr/bin/env python3
"""Generate the reserved OKF wiki index from page frontmatter."""

from __future__ import annotations

import sys
from collections import defaultdict

from run_lib import atomic_write_text
from wiki_lib import ROOT, WIKI_DIR, load_pages

TYPE_ORDER = [
    "Overview",
    "Concept",
    "Entity",
    "Method",
    "Tool",
    "Dataset",
    "Project",
    "Summary",
    "Synthesis",
    "Decision",
    "Contradiction",
    "Reference",
]

HEADINGS = {
    "Overview": "Overview",
    "Concept": "Concepts",
    "Entity": "Entities",
    "Method": "Methods",
    "Tool": "Tools",
    "Dataset": "Datasets",
    "Project": "Projects",
    "Summary": "Summaries",
    "Synthesis": "Syntheses",
    "Decision": "Decisions",
    "Contradiction": "Contradictions",
    "Reference": "References",
}


def main() -> int:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for page in load_pages():
        if page["error"]:
            continue
        page_type = page["frontmatter"].get("type", "Unknown")
        grouped[page_type].append(page)

    lines = [
        "---",
        'okf_version: "0.1"',
        'profile: "llm-wiki-profile/0.2"',
        "---",
        "",
        "# Wiki Index",
        "",
        "This reserved routing file is generated by `tools/build_index.py`.",
        "",
    ]

    for page_type in TYPE_ORDER:
        pages = sorted(grouped.get(page_type, []), key=lambda item: item["wiki_path"])
        if not pages:
            continue
        lines.append(f"## {HEADINGS.get(page_type, page_type)}")
        lines.append("")
        for page in pages:
            fm = page["frontmatter"]
            title = fm.get("title", page["wiki_path"])
            description = fm.get("description") or page["summary"]
            status = fm.get("status", "unknown")
            tags = fm.get("tags", [])
            tag_text = ""
            if tags:
                tag_text = " [" + ", ".join(str(tag) for tag in tags) + "]"
            lines.append(f"- [{title}]({page['wiki_path']}) - {description} ({status}){tag_text}")
        lines.append("")

    index_path = WIKI_DIR / "index.md"
    atomic_write_text(index_path, "\n".join(lines).rstrip() + "\n", ROOT)
    total = sum(len(items) for items in grouped.values())
    print(f"PASS: wrote wiki/index.md with {total} ordinary page entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
